### ISSUE TITLE
No person_hard.pkl

### ISSUE THREAD

**Issue by shadowwalker00** [vinay0410/Pedestrian_Detection#1]
I run the detect file but it returns me with the following error.
`Traceback (most recent call last):
  File "detectmulti.py", line 26, in <module>
    clf = joblib.load("person_hard.pkl")
  File "/anaconda3/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 570, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'person_hard.pkl'`

**Comment by vinay0410** [comment]
I have updated the code please test now. And, remember, in order to get better results as shown in the readme, you might have to decrease the downscale factor.
For, more options which can be passed, please run ```python detectmulti.py -h```.
Also,  I appreciate, you contribution to resolve this issue.

**Comment by vinay0410** [comment]
Hi @shadowwalker00 ,
I am closing this issue due to lack of activity, if you are still facing the same, just reopen it.
